version: '3'

services:
  server:
    build:
      context: ./server
    container_name: server
    restart: always
    environment:
      - NODE_ENV=production
      - GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/firebase-service-account.json
    volumes:
      - ./server/firebase-service-account.json:/app/secrets/firebase-service-account.json:ro
    ports:
      - "3000:3000"
