version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - client
      - server

  client:
    build:
      context: ./client
    container_name: client
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - server

  server:
    build:
      context: ./server
    container_name: server
    restart: always
    environment:
      - NODE_ENV=production
      - COUCHBASE_HOST=10.100.102.15
    ports:
      - "3000:3000"
