version: '3'

services:
  server:
    build:
      context: ./server
    container_name: server
    restart: always
    environment:
      - NODE_ENV=production
      - COUCHBASE_HOST=10.100.102.15
    ports:
      - "3000:3000"
